### ISSUE TITLE
Can't login to whatsapp

### ISSUE THREAD

**Issue by Samsung2023** [getstation/desktop-app#142]
the QR code not showing, Just Loading 
edit: after a while I got error, asking me to update chrome
![image](https://user-images.githubusercontent.com/108600718/213814116-886a15ad-0d90-4d35-be77-9cc72eb12c4f.png)

**Comment by CacaoDan** [comment]
Just installed Station to find the same issue

Any news on a fix?

**Comment by CacaoDan** [comment]
ok thanks

**Comment by LimpingK** [comment]
> no, I switched to another all in one chat

Thank you, I have the same problem. 
I will use rambox.

**Comment by hirschferkel** [comment]
Same problem together with behance and linkedin

**Comment by mawkishdave** [comment]
I am having this issue also and Discord is the same way. When I tried to log in with my email and password it just keeps on the loading screen.

**Comment by viktor44** [comment]
This bug is fixed [here](https://github.com/viktor44/station-desktop-app/releases)

**Comment by CacaoDan** [comment]
> This bug is fixed [here](https://github.com/viktor44/station-desktop-app/releases)

Whatsapp is working, but FB Messenger isn't

I downloaded and installed Station ( a fork of All in one messenger?) and it still doesn't connect to Messenger. I simply get a blank screen

**Comment by viktor44** [comment]
> > This bug is fixed [here](https://github.com/viktor44/station-desktop-app/releases)
> 
> Whatsapp is working, but FB Messenger isn't
> 
> I downloaded and installed Station ( a fork of All in one messenger?) and it still doesn't connect to Messenger. I simply get a blank screen

Yes. That's true. There is a problem with FB Messenger in the [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
#143
